<a href="https://colab.research.google.com/github/Noahkandie/Indigenous-Research-Storytelling/blob/main/Indigenous_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [144]:
import pandas as pd
import numpy as np
import warnings
from warnings import filterwarnings
filterwarnings('ignore')

In [145]:
morara1 = pd.read_csv('/content/morara q1-q3.csv')
morara2 = pd.read_csv('/content/morara q4.csv')
morara3 = pd.read_csv('/content/morara sep.csv')

morara_dfs = [morara1, morara2, morara3]

In [146]:
hanifa_apr_may = pd.read_csv('/content/hanifa apr may.csv')
hanifa_aug = pd.read_csv('/content/hanifa aug.csv')
hanifa_dec = pd.read_csv('/content/hanifa dec.csv')
hanifa_jan1 = pd.read_csv('/content/hanifa jan wk one .csv')
hanifa_jan = pd.read_csv('/content/hanifa jan.csv')
hanifa_jul1 = pd.read_csv('/content/hanifa jul wk.csv')
hanifa_jul = pd.read_csv('/content/hanifa jul.csv')
hanifa_jun = pd.read_csv('/content/hanifa jun.csv')
hanifa_junn = pd.read_csv('/content/hanifa junn.csv')
hanifa_nov = pd.read_csv('/content/hanifa nov.csv')
hanifa_oct = pd.read_csv('/content/hanifa oct.csv')
hanifa_q1 = pd.read_csv('/content/hanifa one.csv')
hanifa_sep  = pd.read_csv('/content/hanifa sept.csv')

hanifa_dfs = [hanifa_apr_may, hanifa_aug, hanifa_dec, hanifa_jan1, hanifa_jan, hanifa_jul1, hanifa_jul, hanifa_jun,hanifa_junn, hanifa_nov, hanifa_oct, hanifa_q1, hanifa_sep]

In [147]:
hanifa_sep['text'].isna().sum()

0

In [148]:
hanifa_q1['text']

0         @Goddess_Rubbi @Eastleighvoice Yes follow us!!
1                                      @IffyIb Yes he is
2      Eastleigh voice, your paper, your voice. @East...
3                          Definitely an inside job damn
4            @aminawaffles ðŸ˜­ðŸ˜­ðŸ˜­ they were soulmates fr fr
                             ...
712                                       @pkoech1_ Lies
713                          @Stephen36920445 I should ðŸ˜‚
714    Yâ€™all not seeing it but heâ€™s making a comeback...
715                      Bro thought itâ€™ll bang lmao ðŸ˜­ðŸ˜­ðŸ˜­
716                              What does kubanja mean?
Name: text, Length: 717, dtype: object

In [149]:
wsr1 = pd.read_csv('/content/wsr one.csv')
wsr2 = pd.read_csv('/content/wsr 2.csv')
wsr3 = pd.read_csv('/content/wsr 3.csv')
wsr4 = pd.read_csv('/content/wsr 4.csv')
wsr5 = pd.read_csv('/content/wsr corr.csv')

wsr_dfs = [wsr1, wsr2, wsr3, wsr4, wsr5]

## Cleaning

In [150]:
def check_missing_columns(dfs, selected_features):
    "Check for missing columns in datasets."
    for i, df in enumerate(dfs):
        missing = [feature for feature in selected_features if feature not in df.columns]
        if missing:
            print(f"Warning: Dataset {i} missing columns: {missing}")

In [151]:
def select_features(df, selected_features):
    "Select available features in a dataset."
    return df[[col for col in selected_features if col in df.columns]].copy()

def fill_missing_text_columns(df, text_columns):
    "Fill missing values in text columns"
    for col in text_columns:
        if col in df.columns:
            df[col] = df[col].astype(str).fillna("")
    return df

In [152]:
def process_datasets(dfs, selected_features):
    "Process datasets by selecting features and handling missing text"
    processed = []
    text_cols = ["text", "quote/text"]
    for df in dfs:
        df_selected = select_features(df, selected_features)
        df_filled = fill_missing_text_columns(df_selected, text_cols)
        processed.append(df_filled)
    return processed

In [153]:
def select_and_concat_datasets(dfs):
    "Select relevant features and concatenate datasets."
    selected_features = [
        "text", "quote/text", "author/description", "author/followers",
        "author/favouritesCount", "author/createdAt", "source", "quote/viewCount",
        "quoteCount", "twitterUrl", "type", "url", "createdAt", "author/location",
        "retweetCount", "replyCount", "likeCount"
    ]

    check_missing_columns(dfs, selected_features)
    processed_dfs = process_datasets(dfs, selected_features)
    return pd.concat(processed_dfs, ignore_index=True, sort=False) if processed_dfs else pd.DataFrame()

In [154]:
# Example

wsr = select_and_concat_datasets(wsr_dfs)

Warning: Dataset 0 missing columns: ['quote/text', 'quote/viewCount', 'likeCount']
Warning: Dataset 1 missing columns: ['quote/text', 'quote/viewCount']
Warning: Dataset 2 missing columns: ['quote/text', 'quote/viewCount']
Warning: Dataset 3 missing columns: ['quote/text', 'quote/viewCount', 'likeCount']

In [155]:
hanifa = select_and_concat_datasets(hanifa_dfs)

Warning: Dataset 0 missing columns: ['replyCount']
Warning: Dataset 5 missing columns: ['retweetCount', 'replyCount']
Warning: Dataset 8 missing columns: ['quote/text', 'twitterUrl', 'retweetCount', 'replyCount']

In [156]:
morara = select_and_concat_datasets(morara_dfs)

In [157]:
df = select_and_concat_datasets([hanifa, morara, wsr])

In [158]:
df.head()

,text,quote/text,author/description,author/followers,author/favouritesCount,author/createdAt,source,quote/viewCount,quoteCount,twitterUrl,type,url,createdAt,author/location,retweetCount,replyCount,likeCount
0,Our latest newspaper edition @Eastleighvoice h...,nan,"Print journalist? I write | Yes,in my mundane,...",281477,43566,Tue Mar 27 14:15:56 +0000 2018,Twitter for iPhone,NaN,2,https://twitter.com/Honeyfarsafi/status/179660...,tweet,https://x.com/Honeyfarsafi/status/179660743141...,Fri May 31 18:19:25 +0000 2024,"Nairobi, Kenya",5.0,NaN,56.0
1,@DiamondDk20 Mine is replacement. Basically ju...,nan,"Print journalist? I write | Yes,in my mundane,...",281477,43566,Tue Mar 27 14:15:56 +0000 2018,Twitter for iPhone,NaN,0,https://twitter.com/Honeyfarsafi/status/179654...,tweet,https://x.com/Honeyfarsafi/status/179654792626...,Fri May 31 14:22:58 +0000 2024,"Nairobi, Kenya",0.0,NaN,16.0
2,The government has totally shocked me today. I...,nan,"Print journalist? I write | Yes,in my mundane,...",281477,43566,Tue Mar 27 14:15:56 +0000 2018,Twitter for iPhone,NaN,17,https://twitter.com/Honeyfarsafi/status/179654...,tweet,https://x.com/Honeyfarsafi/status/179654650881...,Fri May 31 14:17:20 +0000 2024,"Nairobi, Kenya",122.0,NaN,1184.0
3,@maanxur Imagine ðŸ¤£ðŸ¤£ðŸ¤£ðŸ¤£,nan,"Print journalist? I write | Yes,in my mundane,...",281477,43566,Tue Mar 27 14:15:56 +0000 2018,Twitter for iPhone,NaN,0,https://twitter.com/Honeyfarsafi/status/179651...,tweet,https://x.com/Honeyfarsafi/status/179651695954...,Fri May 31 12:19:55 +0000 2024,"Nairobi, Kenya",0.0,NaN,1.0
4,"Please very guided, I get hundreds of calls da...",nan,"Print journalist? I write | Yes,in my mundane,...",281477,43566,Tue Mar 27 14:15:56 +0000 2018,Twitter for iPhone,NaN,1,https://twitter.com/Honeyfarsafi/status/179649...,tweet,https://x.com/Honeyfarsafi/status/179649741360...,Fri May 31 11:02:15 +0000 2024,"Nairobi, Kenya",26.0,NaN,99.0

In [159]:
# look for duplicates

df[df[['createdAt','text']].duplicated()][['createdAt','text']].sort_values('createdAt', ascending=False)

,createdAt,text
7602,Wed Mar 27 11:09:36 +0000 2024,Religious organisations continue to make signi...
7620,Wed Mar 20 12:15:04 +0000 2024,We will support investments in counties â€” thro...
7621,Wed Mar 20 09:51:22 +0000 2024,"Kakamega International Investment Conference, ..."
7622,Wed Mar 20 07:05:28 +0000 2024,"Assented to the Affordable Housing Bill, State..."
7666,Wed Mar 13 17:56:54 +0000 2024,My sincerest condolences to Hon Samuel Tunai f...
...,...,...
7858,Fri Feb 09 10:36:44 +0000 2024,Impressed by the plans of Japanese companies s...
7859,Fri Feb 09 06:49:18 +0000 2024,Our engagement with their Majesties Emperor Na...
7860,Fri Feb 09 06:48:37 +0000 2024,Because of a rich history of consistent friend...
7861,Fri Feb 09 06:48:10 +0000 2024,Kenya is immensely honoured by the warm recept...
7862,Fri Feb 09 06:46:47 +0000 2024,"Our partnership with Japan is strong, dynamic,..."

In [160]:
df.drop_duplicates(subset=['createdAt','text'], inplace=True)

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8439 entries, 0 to 9257
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   text                    8439 non-null   object
 1   quote/text              8439 non-null   object
 2   author/description      8439 non-null   object
 3   author/followers        8439 non-null   int64
 4   author/favouritesCount  8439 non-null   int64
 5   author/createdAt        8439 non-null   object
 6   source                  8439 non-null   object
 7   quote/viewCount         1811 non-null   float64
 8   quoteCount              8439 non-null   int64
 9   twitterUrl              8166 non-null   object
 10  type                    8439 non-null   object
 11  url                     8439 non-null   object
 12  createdAt               8439 non-null   object
 13  author/location         8439 non-null   object
 14  retweetCount            7813 non-null   float64
 15  replyCount              7317 non-null   float64
 16  likeCount               7460 non-null   float64
dtypes: float64(4), int64(3), object(10)
memory usage: 1.2+ MB

In [163]:
df.to_csv('indigenous_data.csv', index=False)